export const productsJSONData = [
  {
    id: 1,
    category: "TXL Primus Motor Oils",
    items: [
      {
        name: "TXL Primus Elite SAE 0W-16 Full Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6B",
        text: ` TXL Primus Elite SAE 0W-16 Full Synthetic Motor Oil, API SP, ILSAC GF-6B is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6B, API SP, API SN Plus, or API SN performance in the SAE 0W-16 viscosity grade. This oil is formulated with synthetic base oils and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        requirements: "",
        currency: "$",
        price: 50,
        id: 1,
      },
      {
        name: "TXL Primus Elite SAE 0W-20 Full Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: ` TXL Primus Elite SAE 0W-20 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with synthetic base oil and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        requirements: `API SP with Resource Conserving, API SN Plus, API SN
  ILSAC GF-6A, GF-5,
  GM dexos1™ Gen 2,
  Chrysler MS6395,
  Ford WSS-M2C947-A (0W-20)`,

        currency: "$",
        price: 50,
        id: 2,
      },
      {
        name: "TXL Primus Elite SAE 5W-20 Full Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: ` TXL Primus Elite SAE 5W-20 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with synthetic base oil and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        requirements: `API SP with Resource Conserving, API SN Plus, API SN
  ILSAC GF-6A, GF-5,
  GM dexos1™ Gen 2,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-20)`,

        currency: "$",
        price: 50,
        id: 3,
      },
      {
        name: "TXL Primus Elite SAE 5W-30 Full Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: `TXL Primus Elite SAE 5W-20 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with synthetic base oil and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        requirements: `API SP with Resource Conserving, API SN Plus, API SN
  ILSAC GF-6A, GF-5,
  GM dexos1™ Gen 2,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-20)`,

        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 4,
      },
      {
        name: "TXL Primus Elite SAE 10W-30 Full Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: ` TXL Primus Elite SAE 10W-30 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with synthetic base oil and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        description: `API SP with Resource Conserving, API SN Plus, API SN
  ILSAC GF-6A, GF-5,
  GM dexos1™ Gen 2,
  Chrysler MS6395`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 5,
      },
      {
        name: "TXL Primus Elite SAE 5W-40 Full Synthetic Motor Oil",
        subTitle: "API SP",
        text: ` TXL Primus Elite SAE 5W-40 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require API SP or API SN performance. This oil is formulated with synthetic base oils and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP, API SN Plus, API SN`,
        currency: "$",
        price: 50,
        id: 6,
      },
      {
        name: "TXL Primus Elite SAE 5W-50 Full Synthetic Motor Oil",
        subTitle: "API SP",
        text: `TXL Primus Elite SAE 5W-50 is a premium full synthetic motor oil manufactured for use in modern gasoline engines that require API SP or API SN performance. This oil is formulated with synthetic base oils and a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP, API SN Plus, API SN`,
        currency: "$",
        price: 50,
        id: 7,
      },
      {
        name: "TXL Primus Elite Euro SAE 5W-30 Full Synthetic Motor Oil",
        subTitle: "ACEA C3, API SN",
        text: `TXL Primus Elite Euro SAE 5W-30 Full Synthetic Motor Oil ACEA C3-16, API SN is formulated with synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel-injected, turbocharged, and supercharged gasoline engines. This oil exceeds the performance requirements of API SN and ACEA C3.`,
        img: "/product-img.png",
        description: `API SN,
  ACEA C3-16,
  BMW LL-04,
  MB 229.31/229.51,
  GM Dexos 2`,
        currency: "$",
        price: 50,
        id: 8,
      },
      {
        name: "TXL Primus Elite Euro SAE 5W-40 Full Synthetic Motor Oil",
        subTitle: "ACEA A3/B4, API SN",
        text: ` TXL Primus Elite Euro SAE 5W-40 Full Synthetic Motor Oil ACEA C3-16, API SN is formulated with synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel-injected, turbocharged, and supercharged gasoline engines. This oil exceeds the performance requirements of API SN and ACEA C3.`,
        img: "/product-img.png",
        description: `ACEA A3/B4-16,
  ACEA A3/B3-16,
  API SN,
  MB 229.3,
  VW 502.00, 505.00,
  BMW LL-01`,
        currency: "$",
        price: 50,
        id: 9,
      },
      {
        name: "TXL Primus Elite SAE 5W-20 Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: ` TXL Primus Elite SAE 5W-20 is a premium synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with a blend of synthetic and Group II paraffinic base oils with a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP with Resource Conserving, API SN Plus, API SN,
  ILSAC GF-6A, GF-5,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-20)`,
        currency: "$",
        price: 50,
        id: 10,
      },
      {
        name: "TXL Primus Elite SAE 5W-30 Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: `TXL Primus Elite SAE 5W-30 is a premium synthetic motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with a blend of synthetic and Group II paraffinic base oils with a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP with Resource Conserving, API SN Plus, API SN,
  ILSAC GF-6A, GF-5,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-30)`,
        currency: "$",
        price: 50,
        id: 11,
      },
      {
        name: "TXL Primus Elite SAE 10W-30 Synthetic Motor Oil",
        subTitle: "API SP, ILSAC GF-6A",
        text: `TXL Primus Elite SAE 10W-30 is a premium synthetic blend motor oil manufactured for use in modern gasoline engines that require ILSAC GF-6A, API SP, API SN Plus, or API SN performance. This oil is formulated with a blend of synthetic and Group II paraffinic base oils with a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP with Resource Conserving, API SN Plus, API SN,
  ILSAC GF-6A, GF-5,
  Chrysler MS6395`,
        currency: "$",
        price: 50,
        id: 12,
      },
      {
        name: "TXL Primus Elite SAE 10W-40 Synthetic Motor Oil",
        subTitle: "API SP",
        text: `TXL Primus SAE 10W-40 is a premium synthetic blend motor oil manufactured for use in modern gasoline engines that require API SP or API SN performance. This oil is formulated with group II paraffinic and synthetic base oils as well as a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP, API SN Plus, API SN`,
        currency: "$",
        price: 50,
        id: 13,
      },
      {
        name: "TXL Primus SAE 20W-50 Synthetic Tech Motor Oil",
        subTitle: "API SP",
        text: `TXL Primus SAE 20W-50 is a premium synthetic blend motor oil manufactured for use in modern gasoline engines that require API SP or API SN performance. This oil is formulated with group II paraffinic and synthetic base oils as well as a premium performance additive package, which is specially formulated to protect high-compression gasoline direct injection engines, delivering superior oxidative stability, deposit control, low-speed pre-ignition mitigation, and timing chain wear protection.`,
        img: "/product-img.png",
        description: `API SP, API SN Plus, API SN`,
        currency: "$",
        price: 50,
        id: 14,
      },
    ],
  },
  {
    id: 2,
    category: "TXL Teres Motor Oils",
    items: [
      {
        name: "TXL Teres Elite SAE 0W-20 Full Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Elite Full Synthetic Motor Oils, SAE 0W-20, API SN, ILSAC GF-5 is formulated with synthetic base oils and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. This oil exceeds the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  Ford WSS-M2C947-A`,
        currency: "$",
        price: 50,
        id: 15,
      },
      {
        name: "TXL Teres Elite SAE 5W-20 Full Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Elite Full Synthetic Motor Oil 5W-20 formulated with synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. Exceed the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-20)`,
        currency: "$",
        price: 50,
        id: 16,
      },
      {
        name: "TXL Teres Elite SAE 5W-30 Full Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Elite Full Synthetic Motor Oil 5W-30 formulated with synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. Exceed the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  Ford WSS-M2C945-A (5W-30)`,
        description: ``,
        currency: "$",
        price: 50,
        id: 17,
      },
      {
        name: "TXL Teres Elite SAE 10W-30 Full Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: ` TXL Teres Elite Full Synthetic Motor Oil 10W-30 formulated with synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. This oil exceeds the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395`,
        currency: "$",
        price: 50,
        id: 18,
      },
      {
        name: "TXL Teres Elite SAE 5W-20 Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Synthetic Motor Oil, SAE 5W-20, API SN, ILSAC GF-5 formulated with a blend of conventional and synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. Exceed the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        description: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  GM6094M,
  Ford WSS-M2C945-A (5W-20)`,
        currency: "$",
        price: 50,
        id: 19,
      },
      {
        name: "TXL Teres Elite SAE 5W-30 Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Synthetic Motor Oil, SAE 5W-30, API SN, ILSAC GF-5 formulated with a blend of conventional and synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. Exceed the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN with Resource Conserving, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  GM6094M,
  Ford WSS-M2C945-A (5W-30)`,
        currency: "$",
        price: 50,
        id: 20,
      },
      {
        name: "TXL Teres Elite SAE 10W-30 Synthetic Motor Oil",
        subTitle: "API SN, ILSAC GF-5A",
        text: `TXL Teres Synthetic Motor Oil, SAE 10W-30, API SN, ILSAC GF-5 formulated with a blend of conventional and synthetic base oil and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged gasoline engines. Exceed the performance requirements of API SN and ILSAC GF-5.`,
        img: "/product-img.png",
        requirements: `API SN, API SM, API SL, API SJ,
  ILSAC GF-5,
  Chrysler MS6395,
  GM6094M`,
        currency: "$",
        price: 50,
        id: 21,
      },
      {
        name: "TXL Primus Elite SAE 10W-40 Synthetic Motor Oil",
        subTitle: "API SN",
        text: ` TXL Teres Synthetic Motor Oil, SAE 20W-50 API SN Plus is formulated with a blend of conventional and synthetic base oils and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged and supercharged gasoline engines in both normal and extreme operating conditions. This oil exceeds the performance requirements of API SN.`,
        img: "/product-img.png",
        requirements: `API SN, API SM, API SL, API SJ`,
        currency: "$",
        price: 50,
        id: 22,
      },
      {
        name: "TXL Teres SAE 20W-50 Synthetic Tech Motor Oil",
        subTitle: "API SN",
        text: `TXL Teres Synthetic Motor Oil, SAE 20W-50 API SN Plus is formulated with a blend of conventional and synthetic base oils and a premium additive package. This oil is designed for use in carbureted, fuel injected, turbocharged and supercharged gasoline engines in both normal and extreme operating conditions. This oil exceeds the performance requirements of API SN.`,
        img: "/product-img.png",
        requirements: `API SN, API SM, API SL, API SJ`,
        currency: "$",
        price: 50,
        id: 23,
      },
      {
        name: "TXL Teres SAE 30 HD Synthetic Tech Motor Oil",
        subTitle: "API SN/CF",
        text: ` Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta velit quis harum aut omnis a quasi odit ipsum aspernatur pariatur ab eligendi officia, fuga, vero deserunt cum qui iure ducimus!
  `,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 24,
      },
      {
        name: "TXL Teres SAE 40 HD Synthetic Tech Motor Oil",
        subTitle: "API SN/CF",
        text: ` Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta velit quis harum aut omnis a quasi odit ipsum aspernatur pariatur ab eligendi officia, fuga, vero deserunt cum qui iure ducimus!
  `,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 25,
      },
      {
        name: "TXL Teres SAE 50 HD Synthetic Tech Motor Oil",
        subTitle: "API SN/CF",
        text: ` Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dicta velit quis harum aut omnis a quasi odit ipsum aspernatur pariatur ab eligendi officia, fuga, vero deserunt cum qui iure ducimus!
  `,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 26,
      },
    ],
  },
  {
    id: 3,
    category: "TXL Fortis Heavy-Duty Engine Oils",
    items: [
      {
        name: "TXL Fortis Elite SAE 5W-30 Full Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Full Synthetic Heavy-Duty Motor Oil SAE 5W-30 is formulated with synthetic base oil and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Full Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,

        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 101,
      },
      {
        name: "TXL Fortis Elite SAE 10W-30 Full Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Full Synthetic Heavy-Duty Motor Oil SAE 5W-30 is formulated with synthetic base oil and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Full Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 27,
      },
      {
        name: "TXL Fortis Elite SAE 5W-40 Full Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Full Synthetic Heavy-Duty Motor Oil SAE 5W-40 is formulated with synthetic base oils and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Full Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 28,
      },
      {
        name: "TXL Fortis Elite SAE 10W-40 Full Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Full Synthetic Heavy-Duty Motor Oil SAE 10W-40 is formulated with synthetic base oils and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Full Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 29,
      },
      {
        name: "TXL Fortis Elite SAE 15W-40 Full Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Full Synthetic Heavy-Duty Motor Oil SAE 15W-40 is formulated with synthetic base oils and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Full Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 30,
      },
      {
        name: "TXL Fortis Elite SAE 10W-30 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Elite Synthetic Heavy-Duty Motor Oil SAE 10W-30 is formulated with synthetic base oils and a premium additive package. This oil is designed for use in for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. This oil is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis Elite Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 31,
      },
      {
        name: "TXL Fortis Elite SAE 15W-40 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CK-4/SN",

        text: `TXL Fortis Synthetic Heavy-Duty Engine Oil, SAE 15W-40, API CK-4/SN, is formulated with conventional and synthetic base oil and a premium additive package. This oil is designed for use in high-speed four-stroke cycle diesel engines designed to meet 2017 model year on-highway and Tier 4 non-road exhaust emission standards as well as for previous model year diesel engines. It is especially effective at sustaining emission control system durability where particulate filters and other advanced after-treatment systems are used. TXL Fortis SAE 10W-30 and 15W-40 Synthetic Heavy-Duty Diesel Engine Oils API Service CK-4/SN provide enhanced protection against oil oxidation, viscosity loss due to shear, and oil aeration as well as protection against catalyst poisoning, particulate filter blocking, engine wear, piston deposits, degradation of low- and high-temperature properties, and soot-related viscosity increase. In addition to API CK-4, this oil exceeds the performance criteria of CJ-4, CI-4 with CI-4 PLUS, CI-4, and CH-4 and can effectively lubricate engines calling for those API Service Categories. When using this product in conjunction with fuel containing higher than 15 ppm of sulfur, consult the engine manufacturer for service interval recommendations.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 32,
      },
      {
        name: "TXL Fortis Elite SAE 15W-50 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CJ-4/SN",

        text: `TXL Fortis Synthetic Blend Heavy-Duty Engine Oil, SAE 15W-50, API CJ-4/SN parasynthetic crankcase lubricants for use in modern diesel engines. Formulated with a blend of synthetic and conventional base oil as well as a premium quality additive package, this oil exhibits excellent detergent, dispersant, anti-wear, anti-corrosion, anti-oxidant, and anti-foaming properties.`,
        requirements: `API CJ-4, CI-4 Plus, CI-4, CH-4, CF-4, CF-2, CF
API SN, SM, SL, SJ, SG`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 33,
      },
      {
        name: "TXL Fortis Elite SAE 20W-50 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CJ-4/SN",

        text: `TXL Fortis Synthetic Blend Heavy-Duty Engine Oil, SAE 20W-50, API CJ-4/SN parasynthetic crankcase lubricants for use in modern diesel engines. Formulated with a blend of synthetic and conventional base oil as well as a premium quality additive package, this oil exhibits excellent detergent, dispersant, anti-wear, anti-corrosion, anti-oxidant, and anti-foaming properties.`,
        requirements: `API CJ-4, CI-4 Plus, CI-4, CH-4, CF-4, CF-2, CF
API SN, SM, SL, SJ, SG`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 34,
      },
      {
        name: "TXL Fortis Elite SAE 15W-40 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CI-4/SL, CI-4 Plus",

        text: `TXL Fortis Synthetic Blend Heavy-Duty Engine Oil, SAE 15W-40, API CI-4/SL, CI-4 Plus is a parasynthetic crankcase lubricant for use in modern diesel engines. Formulated with a blend of synthetic and conventional base oils as well as a premium quality additive package, this oil exhibits excellent detergent, dispersant, anti-wear, anti-corrosion, anti-oxidant, and anti-foaming properties.`,
        requirements: `API CI-4 Plus, CI-4, CH-4, CF-4, CF-2, CF
API SL, SJ, SG, SF,
ACEA E7,
Cummins CES 20078,
MB 228.1, 229.1,
MAN 271,
MTU Type 1,
Volvo VDS-2,
Mack EO-M Plus,
Renault Truck RD/RD-2,
CAT ECF-1-
ZF TE-ML 07C`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 35,
      },
      {
        name: "TXL Fortis Elite SAE 20W-50 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CI-4/SL, CI-4 Plus",

        text: `TXL Fortis Synthetic Blend Heavy-Duty Engine Oil, SAE 20W-50, API CI-4/SL, CI-4 Plus is a parasynthetic crankcase lubricant for use in modern diesel engines. Formulated with a blend of synthetic and conventional base oils as well as a premium quality additive package, this oil exhibits excellent detergent, dispersant, anti-wear, anti-corrosion, anti-oxidant, and anti-foaming properties.`,
        requirements: `API CI-4 Plus, CI-4, CH-4, CF-4, CF-2, CF
API SL, SJ, SG, SF,
ACEA E7,
Cummins CES 20078,
MB 228.1, 229.1,
MAN 271,
MTU Type 1,
Volvo VDS-2,
Mack EO-M Plus,
Renault Truck RD/RD-2,
CAT ECF-1-
ZF TE-ML 07C`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 36,
      },
      {
        name: "TXL Fortis Elite SAE 20W-50 Synthetic Heavy-Duty Engine Oil",
        subTitle: "API CH-4/SL",

        text: `TXL Fortis Viridis Synthetic Blend Heavy-Duty Engine Oil, SAE 25W-60, API CH-4/SL is a parasynthetic crankcase lubricant for use in modern diesel engines. Formulated with a blend of synthetic and conventional base oil as well as a premium quality additive package, this oil exhibits good detergent, dispersant, anti-wear, anti-corrosion, anti-oxidant, and anti-foaming properties.`,
        requirements: `API CH-4, CF-4, CF-2, CF
API SL, SJ, SG, SF`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 37,
      },
      {
        name: "TXL Fortis SAE 15W-40 Synthetic Tech Heavy-Duty Engine Oil",
        subTitle: "API CJ-4/SN",
        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 38,
      },
    ],
  },
  {
    id: 4,
    category: "TXL Gravis Gear Oils",
    items: [
      {
        name: "TXL Gravis Elite SAE 75W-90 Synthetic Gear Oil",
        subTitle: "",

        text: `TXL GRAVIS ELITE 75W-90 is formulated with synthetic base oil and specialty performance additives to provide improved high-temperature thermal and oxidative stability in a wide range of operating conditions. Specialty anti-scuffing additives and friction modifiers provide advanced protection and lubricity in extreme pressure conditions. Additionally, TXL GRAVIS ELITE SYNTHETIC LIMITED SLIP GEAR OIL is highly shear stable while also resisting rust, oxidation, foaming, and varnish. TXL GRAVIS ELITE 75W-90, API GL-5, MT-1 SYNTHETIC GEAR OIL is designed for use in all seasons and exceeds the year-around, all-weather performance viscosity requirements of SAE J306 as well as the rigorous performance requirements of API GL-5 and MT-1. API Category GL-5 designates the type of service characteristic of gears, particularly hypoids in automotive axles under high-speed and/or low-speed, high-torque conditions. Lubricants meeting API MT-1 provide protection against the combination of thermal degradation, component wear, and oil seal deterioration which is not provided by lubricants meeting only the requirements of API GL-5. This oil also meets or exceeds the performance requirements of the following industry and OEM specifications: API GL-5, API MT-1, Mack GO-J Plus (75W-90), SAE J2360, and Meritor O76-E.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 39,
      },
      {
        name: "TXL Gravis Elite SAE 75W-140 Synthetic Gear Oil",
        subTitle: "",

        text: `TXL GRAVIS ELITE 75W-140 is formulated with synthetic base oil and specialty performance additives to provide improved high-temperature thermal and oxidative stability in a wide range of operating conditions. Specialty anti-scuffing additives and friction modifiers provide advanced protection and lubricity in extreme pressure conditions. Additionally, TXL GRAVIS ELITE SYNTHETIC LIMITED SLIP GEAR OIL is highly shear stable while also resisting rust, oxidation, foaming, and varnish. TXL GRAVIS ELITE 75W-90, API GL-5, MT-1 SYNTHETIC GEAR OIL is designed for use in all seasons and exceeds the year-around, all-weather performance viscosity requirements of SAE J306 as well as the rigorous performance requirements of API GL-5 and MT-1. API Category GL-5 designates the type of service characteristic of gears, particularly hypoids in automotive axles under high-speed and/or low-speed, high-torque conditions. Lubricants meeting API MT-1 provide protection against the combination of thermal degradation, component wear, and oil seal deterioration which is not provided by lubricants meeting only the requirements of API GL-5. This oil also meets or exceeds the performance requirements of the following industry and OEM specifications: API GL-5, API MT-1, Mack GO-J Plus (75W-140), SAE J2360, and Meritor O76-E.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 40,
      },
      {
        name: "TXL Gravis Elite SAE 80W-140 Synthetic Gear Oil",
        subTitle: "",

        text: `TXL GRAVIS ELITE 80W-140 is formulated with synthetic base oil and specialty performance additives to provide improved high-temperature thermal and oxidative stability in a wide range of operating conditions. Specialty anti-scuffing additives and friction modifiers provide advanced protection and lubricity in extreme pressure conditions. Additionally, TXL GRAVIS ELITE SYNTHETIC LIMITED SLIP GEAR OIL is highly shear stable while also resisting rust, oxidation, foaming, and varnish. TXL GRAVIS ELITE 80W-140, API GL-5, MT-1 SYNTHETIC GEAR OIL is designed for use in all seasons and exceeds the year-around, all-weather performance viscosity requirements of SAE J306 as well as the rigorous performance requirements of API GL-5 and MT-1. API Category GL-5 designates the type of service characteristic of gears, particularly hypoids in automotive axles under high-speed and/or low-speed, high-torque conditions. Lubricants meeting API MT-1 provide protection against the combination of thermal degradation, component wear, and oil seal deterioration which is not provided by lubricants meeting only the requirements of API GL-5. This oil also meets or exceeds the performance requirements of the following industry and OEM specifications: API GL-5, API MT-1, Mack GO-J Plus (80W-140), SAE J2360, and Meritor O76-E.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 41,
      },
      {
        name: "TXL Gravis Elite SAE 40 Synthetic HD Transmission Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 42,
      },
      {
        name: "TXL Gravis Elite SAE 50 Synthetic HD Transmission Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 43,
      },
      {
        name: "TXL Gravis Elite SAE 80W-90 Gear Oil",
        subTitle: "",

        text: `TXL GRAVIS ELITE 80W-90 is formulated with base oil and specialty performance additives to provide improved high-temperature thermal and oxidative stability in a wide range of operating conditions. Specialty anti-scuffing additives and friction modifiers provide advanced protection and lubricity in extreme pressure conditions. Additionally, TXL GRAVIS ELITE LIMITED SLIP GEAR OIL is highly shear stable while also resisting rust, oxidation, foaming, and varnish. TXL GRAVIS ELITE 80W-90, API GL-5, MT-1 SYNTHETIC GEAR OIL is designed for use in all seasons and exceeds the year-around, all-weather performance viscosity requirements of SAE J306 as well as the rigorous performance requirements of API GL-5 and MT-1. API Category GL-5 designates the type of service characteristic of gears, particularly hypoids in automotive axles under high-speed and/or low-speed, high-torque conditions. Lubricants meeting API MT-1 provide protection against the combination of thermal degradation, component wear, and oil seal deterioration which is not provided by lubricants meeting only the requirements of API GL-5. This oil also meets or exceeds the performance requirements of the following industry and OEM specifications: API GL-5, API MT-1, Mack GO-J Plus (80W-140), SAE J2360, and Meritor O76-E.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 44,
      },
      {
        name: "TXL Gravis SAE 85W-140 Gear Oil",
        subTitle: "",

        text: `TXL GRAVIS 85W-140 API GL-5 GEAR OIL formulated with high viscosity-index, paraffinic base oil and specialty performance additives. API Category GL-5 designates the type of service characteristic of gears, particularly hypoids in automotive axles under high-speed and/or low-speed, high-torque conditions. Specialty anti-scuffing additives and friction modifiers provide advanced protection and lubricity in extreme pressure conditions. Additionally, TXL GRAVIS 85W-140 API GL-5 GEAR OIL is highly shear stable while also resisting rust, oxidation, foaming, and varnish.

`,
        requirements: `API GL-5`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 45,
      },
    ],
  },

  {
    id: 5,
    category: "TXL Optimum Transmission Fluids",
    items: [
      {
        name: "TXL Optimum Elite Synthetic Multi-Vehicle ATF",
        subTitle: "",

        text: `Formulated with synthetic base stocks and premium performance additives, TXL OPTIMUM ELITE SYNTHETIC MULTI-VEHICLE ATF is a premium-grade, low-viscosity synthetic automatic transmission lubricant. This product contains a premium performance additive package designed for excellent oxidation stability and thermal resistance, as well as excellent friction modification properties. TXL OPTIMUM ELITE SYNTHETIC MULTI-VEHICLE ATF is a multipurpose automatic transmission lubricant that is suitable for use in applications that require GM DEXRON® VI as well as a variety of North American, Asian, and European passenger car applications requiring low viscosity ATF.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 46,
      },
      {
        name: "TXL Optimum Full Synthetic HD ATF",
        subTitle: "",

        text: `Optimum Elite Full Synthetic HD ATF is a high-viscosity, multi-vehicle full synthetic heavy-duty automatic transmission fluid designed for exceptional performance in a myriad of heavy-duty truck and passenger vehicle automatic transmission fluid applications. This product is formulated with synthetic base oils and a premium performance additive package to provide outstanding oxidation stability, frictional properties, resistance to sludge and varnish, and anti-wear protection. This ATF provides optimal frictional characteristics to prevent stick, slip, or shudder, as well as excellent shudder durability to provide smooth shifting and clutch performance throughout the lifetime of the product.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 47,
      },
      {
        name: "TXL Optimum Elite Full Synthetic CVT Fluid",
        subTitle: "",

        text: `TXL Optimum Elite Full Synthetic CVT Fluid is a fully synthetic continuously variable transmission lubricant reinforced with a premium transmission additive package specifically designed to provide superior protection and performance to chain or push belt continuously variable transmissions. Suitable for use in most CVT applications, TXL Optimum Elite Full Synthetic CVT Fluid exhibits outstanding shear stability (stay-in-grade viscometrics) as well as excellent anti-scuffing properties to protect against metal-to-metal wear. Furthermore, the premium synthetic base stock utilized provides outstanding oxidation stability coupled with excellent low temperature properties.`,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 48,
      },
      {
        name: "TXL Optimum Elite Full Synthetic DCT Fluid",
        subTitle: "",

        text: `TXL Optimum Elite Full Synthetic DCT Fluid is a premium full synthetic Dual Clutch Transmission Fluid designed for use in most Wet Dual Clutch Transmissions in North America, Europe, and Asia. This fluid exhibits excellent oxidation and corrosion protection coupled with outstanding friction durability to provide smooth shift feel. Additionally, this fluid provides good seal compatibility and wear protection to provide critical protection to seal and gear box components.

`,
        requirements: `VW TL 052 182, TL 052 529,
BMW 83 22 2 148 578, 83 22 2 148 579, 83 22 0 440 214, 83 22 2 147 477 (BMW DCTF-1),
Peugeot/Citroen 9734.S2,
Fiat BOT 341,
Ford M2C936A (BOT 341),
MB 236.21, 236.25,
MZ320065 Dia-Queen SSTF-I,
Porsche Oil No. 999.917.080.00 (FFL-3),
Renault BOT 450,
Volvo 1161838, 1161839`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 49,
      },
      {
        name: "TXL Optimum Multi-Purpose ATF",
        subTitle: "",

        text: `TXL Optimum Multi-Purpose ATF is a quality automatic transmission fluid that is suitable for use in applications that require GM Dexron III or Ford Mercon specification fluids, as well as most other pre-2006 ATF applications. This product is formulated with group II paraffinic base stocks and a performance additive package to provide adequate anti-shudder, anti-oxidant, anti-wear, and anti-foam properties. This oil is also suitable for use as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.

`,
        requirements: `GM Dexron III-H, II-E, II,
Ford Mercon,
Allison C-4, TES-389,

NOT Recommended for Ford Type F Fluids, or any ATF application specification newer than 2006, such as Dexron VI, Mercon V, or Mercon LV.`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 50,
      },
    ],
  },
  {
    id: 6,
    category: "TXL Durus Off-Road Lubricants",
    items: [
      {
        name: "TXL Durus Elite Tractor Hydraulic Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 51,
      },
      {
        name: "TXL Durus Premium Tractor Hydraulic Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 52,
      },
      {
        name: "TXL Durus SAE 10W-30 Super Tractor Oil Universal Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 53,
      },
      {
        name: "TXL Durus SAE 15W-40 Super Tractor Oil Universal Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 54,
      },
      {
        name: "TXL Durus SAE 10W HD Transmission Drivetrain Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 55,
      },
      {
        name: "TXL Durus SAE 30 HD Transmission Drivetrain Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 56,
      },
      {
        name: "TXL Durus SAE 50 HD Transmission Drivetrain Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 57,
      },
      {
        name: "Synehex Durus Multiplex Transmission Drivetrain Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 58,
      },
    ],
  },

  {
    id: 7,
    category: "TXL Frictio 4T Engine Oils",
    items: [
      {
        name: "TXL Frictio Elite SAE 5W-30 Full Synthetic 4T Engine Oil",
        subTitle: "API SN, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 59,
      },
      {
        name: "TXL Frictio Elite SAE 5W-40 Full Synthetic 4T Engine Oil",
        subTitle: "API SN, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 60,
      },
      {
        name: "TXL Frictio Elite SAE 10W-50 Full Synthetic 4T Engine Oil",
        subTitle: "API SN, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 61,
      },
      {
        name: "TXL Frictio SAE 10W-30 Synthetic Tech 4T Engine Oil",
        subTitle: "API SL, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 62,
      },
      {
        name: "TXL Frictio SAE 10W-40 Synthetic Tech 4T Engine Oil",
        subTitle: "API SL, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 63,
      },
      {
        name: "TXL Frictio SAE 20W-50 Synthetic Tech 4T Engine Oil",
        subTitle: "API SL, JASO MA2",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 64,
      },
    ],
  },
  {
    id: 8,
    category: "TXL Altum Hydraulic Oils",
    items: [
      {
        name: "TXL Altum Elite Multiplex ISO VG 22 HVI AW Synthetic Hydraulic Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 65,
      },
      {
        name: "TXL Altum Elite Multiplex ISO VG 32 HVI AW Synthetic Hydraulic Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 66,
      },
      {
        name: "TXL Altum Elite Multiplex ISO VG 46 HVI AW Synthetic Hydraulic Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 67,
      },
      {
        name: "TXL Altum Elite Multiplex ISO VG 68 HVI AW Synthetic Hydraulic Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 68,
      },
      {
        name: "TXL Altum ISO VG 22 AW Hydraulic Oil",
        subTitle: "",

        text: `Formulated with high viscosity-index paraffinic base stocks and premium performance additives, TXL Altum AW Hydraulic Oil ISO VG 22 exhibits excellent oxidation stability, corrosion protection, shear stability, and pumpability in a wide array of operating conditions and temperatures. The comprehensive additive package includes anti-wear, anti-corrosion, anti-foaming agents as well as detergency. Acceptable for a wide range of applications, TXL Altum AW Hydraulic Oil ISO VG 22 AW resists oxidation, rust, corrosion, foaming, varnish, and wear. It is used as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.

`,
        requirements: `Parker Denison HF-0, HF-1, HF-2)
GM LS-2,
JCMAS HK,
U.S. Steel 127,
U.S. Steel 136,
Bosch Rexroth RD90220,
SAE MS1004`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 69,
      },

      {
        name: "TXL Altum ISO VG 32 AW Hydraulic Oil",
        subTitle: "",

        text: `Formulated with high viscosity-index paraffinic base stocks and premium performance additives, TXL Altum AW Hydraulic Oil ISO VG 32 exhibits excellent oxidation stability, corrosion protection, shear stability, and pumpability in a wide array of operating conditions and temperatures. The comprehensive additive package includes anti-wear, anti-corrosion, anti-foaming agents as well as detergency. Acceptable for a wide range of applications, TXL Altum AW Hydraulic Oil ISO VG 32 AW resists oxidation, rust, corrosion, foaming, varnish, and wear. It is used as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.

`,
        requirements: `Parker Denison HF-0, HF-1, HF-2)
GM LS-2,
JCMAS HK,
U.S. Steel 127,
U.S. Steel 136,
Bosch Rexroth RD90220,
SAE MS1004`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 70,
      },
      {
        name: "TXL Altum ISO VG 46 AW Hydraulic Oil",
        subTitle: "",

        text: `Formulated with high viscosity-index paraffinic base stocks and premium performance additives, TXL Altum AW Hydraulic Oil ISO VG 46 exhibits excellent oxidation stability, corrosion protection, shear stability, and pumpability in a wide array of operating conditions and temperatures. The comprehensive additive package includes anti-wear, anti-corrosion, anti-foaming agents as well as detergency. Acceptable for a wide range of applications, TXL Altum AW Hydraulic Oil ISO VG 46 AW resists oxidation, rust, corrosion, foaming, varnish, and wear. It is used as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.`,
        requirements: `Parker Denison HF-0, HF-1, HF-2)
GM LS-2,
JCMAS HK,
U.S. Steel 127,
U.S. Steel 136,
Bosch Rexroth RD90220,
SAE MS1004`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 71,
      },
      {
        name: "TXL Altum ISO VG 68 AW Hydraulic Oil",
        subTitle: "",

        text: `Formulated with high viscosity-index paraffinic base stocks and premium performance additives, TXL Altum AW Hydraulic Oil ISO VG 68 exhibits excellent oxidation stability, corrosion protection, shear stability, and pumpability in a wide array of operating conditions and temperatures. The comprehensive additive package includes anti-wear, anti-corrosion, anti-foaming agents as well as detergency. Acceptable for a wide range of applications, TXL Altum AW Hydraulic Oil ISO VG 68 AW resists oxidation, rust, corrosion, foaming, varnish, and wear. It is used as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.

`,
        requirements: `Parker Denison HF-0, HF-1, HF-2)
GM LS-2,
JCMAS HK,
U.S. Steel 127,
U.S. Steel 136,
Bosch Rexroth RD90220,
SAE MS1004`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 72,
      },
      {
        name: "TXL Altum ISO VG 100 AW Hydraulic Oil",
        subTitle: "",

        text: `Formulated with high viscosity-index paraffinic base stocks and premium performance additives, TXL Altum AW Hydraulic Oil ISO VG 100 exhibits excellent oxidation stability, corrosion protection, shear stability, and pumpability in a wide array of operating conditions and temperatures. The comprehensive additive package includes anti-wear, anti-corrosion, anti-foaming agents as well as detergency. Acceptable for a wide range of applications, TXL Altum AW Hydraulic Oil ISO VG 100 AW resists oxidation, rust, corrosion, foaming, varnish, and wear. It is used as a power steering fluid, hydraulic fluid, and/or industrial fluid when a “Dexron III/Mercon” type ATF is recommended.`,
        requirements: `Parker Denison HF-0, HF-1, HF-2)
GM LS-2,
JCMAS HK,
U.S. Steel 127,
U.S. Steel 136,
Bosch Rexroth RD90220,
SAE MS1004`,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 73,
      },
    ],
  },
  {
    id: 9,
    category: "TXL Probus Industrial Oils",
    items: [
      {
        name: "TXL Probus Elite ISO 68 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 74,
      },
      {
        name: "TXL Probus Elite ISO 100 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 75,
      },
      {
        name: "TXL Probus Elite ISO 150 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 76,
      },
      {
        name: "TXL Probus Elite ISO 220 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 77,
      },
      {
        name: "TXL Probus Elite ISO 320 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 78,
      },
      {
        name: "TXL Probus Elite ISO 460 EP Synthetic Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 79,
      },
      {
        name: "TXL Probus ISO VG 68 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 80,
      },
      {
        name: "TXL Probus ISO VG 100 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 81,
      },
      {
        name: "TXL Probus ISO VG 150 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 82,
      },
      {
        name: "TXL Probus ISO VG 220 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 83,
      },
      {
        name: "TXL Probus ISO VG 320 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 84,
      },
      {
        name: "TXL Probus ISO VG 460 EP Gear Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 85,
      },
      {
        name: "TXL Probus ISO VG 10 Spindle Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 86,
      },
      {
        name: "TXL Probus ISO VG 15 Spindle Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 87,
      },
      {
        name: "TXL Probus ISO VG 22 Spindle Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 88,
      },
      {
        name: "TXL Probus ISO VG 68 Way Lube",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 89,
      },
      {
        name: "TXL Probus ISO VG 220 Way Lube",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 90,
      },
      {
        name: "TXL Probus HTF-42 Heat Transfer Fluid",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 91,
      },
      {
        name: "TXL Probus ISO VG 32 Turbine Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 92,
      },
      {
        name: "TXL Probus ISO VG 46 Turbine Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 93,
      },
      {
        name: "TXL Probus ISO VG 68 Turbine Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 94,
      },
    ],
  },
  {
    id: 10,
    category: "TXL Duo 2-Cycle Engine Oil",
    items: [
      {
        name: "TXL Duo Elite Synthetic 2-Cycle Engine Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 95,
      },
      {
        name: "TXL Duo 2-Cycle Engine Oil",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 96,
      },
    ],
  },
  {
    id: 11,
    category: "TXL Certus Gas Engine Oils",
    items: [
      {
        name: "TXL Certus GEO 717 SAE 30",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 97,
      },
      {
        name: "TXL Certus GEO 717 SAE 40",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 98,
      },
      {
        name: "TXL Certus GEO 717 SAE 15W-40",
        subTitle: "",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 99,
      },
      {
        name: "TXL Certus GEO 700 (CNG/LNG) HD SAE 15W-40",
        subTitle: "API CK-4/SN",

        text: ``,
        requirements: ``,
        img: "/product-img.png",
        currency: "$",
        price: 50,
        id: 100,
      },
    ],
  },
]
